services:
  app:
    build:
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    env_file: .env
    command: npm run start:debug:container
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 3s
      retries: 3
volumes:
  postgres: