export const SCENE_METADATA = 'SCENE_METADATA';
export const SCENE_METHODS_METADATA = 'SCENE_METHODS_METADATA';
export const SCENE_COMPOSER_METHOD_METADATA = 'SCENE_COMPOSER_METHOD_METADATA';
export const PLUGIN_METADATA = 'PLUGIN_METADATA';
